### ISSUE TITLE
Any Update For Language English ? 

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/DuRevitTools#1]
Hi weianweigan, 
you want update it for multi language , we can collaboration?

**Comment by weianweigan** [comment]
@chuongmep It's using english.Do you mean translate project templates to multi language or add some features for it?

**Comment by chuongmep** [comment]
Yes, we can do that ? And fix some error drag panel with visual studio 2019 preview

**Comment by weianweigan** [comment]
yes,do you have a todo-list specifically or what languages and features to add? I am using vs2019 without preview and I dont know about the drag panel error with the preview version.

**Comment by chuongmep** [comment]
I have, i think we will update some : 
- Multi Language 
- Kill Revit
- Xml Generator
- Setting Path Default Copy instead Copy Event when build dll

**Comment by weianweigan** [comment]
It's ok. What to you want to do in the list, i could do the rest of it when i have free time.
